name: 'ms-teams-notify'
description: 'Notify Action for MS Teams'
author: 'chrisyates-sage'
inputs:
  message:
    description: 'Message'
    required: false
    default: Test started from ${{ github.event_name }}
  teamsurl:
    description: 'Full URL for Teams room'
    required: false
    default: https://outlook.office.com/webhook/4debbfbb-c394-4de0-a0eb-3cd444c9554e@3e32dd7c-41f6-492d-a1a3-c58eb02cf4f8/IncomingWebhook/2aac373336894c12b3db5d43c350af17/2b82dd20-1338-4397-807d-e05538020cef
runs:
  using: 'node12'
  main: 'index.js'
